repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args:
          - "--max-line-length=79"
          - "--max-complexity=18"
          - "--ignore=E501,W503,E203,F401,D400,D205,D401,D202,T001,D105"
        additional_dependencies:
          [
              "flake8-bugbear==19.8.0",
              "flake8-coding==1.3.2",
              "flake8-comprehensions==3.0.1",
              "flake8-debugger==3.2.1",
              "flake8-deprecated==1.3",
              "flake8-pep3101==1.2.1",
              "flake8-polyfill==1.0.2",
              "flake8-print==3.1.4",
              "flake8-string-format==0.2.3",
              "flake8-docstrings==1.5.0",
          ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: pretty-format-json
        args: [ '--no-sort-keys' ]
      - id: no-commit-to-branch
        args: [ --branch, master ]
      - id: no-commit-to-branch
        args: [ --branch, main ]
