name: Continuous Integration

on:
  push:
    branches:
      - main
      - master
  release:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - python-version: ["3.10", 3.11, 3.12]

    steps:
      - uses: actions/checkout@v4
      - name: Set up testing python ${{ matrix.config.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.config.python-version }}
      - name: Python poetry action
        uses: abatilo/actions-poetry@v2.3.0
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:ubuntugis/ppa && sudo apt-get update && sudo apt-get install -y build-essential gdal-bin libgdal-dev
      - name: Pytest
        run: poetry run pytest -x --random-order

  build-and-publish:
    name: Build and publish Python distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-22.04
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - name: Set up base Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.3.0
      - name: Publish distribution 📦 with test.pypi.org
        if: startsWith(github.ref, 'refs/tags')
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_TOKEN }}
          poetry build
          poetry publish -r testpypi
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
          poetry build
          poetry publish
